project:
  type: website

website:
  title: "Piracy"
  navbar:
    left:
      - href: consumers.qmd
        text: Consumer
      - href: creators.qmd
        text: Creator
      - href: ownership.qmd
        text: Ownership

format:
  html:
    theme:
      - slate
      - brand
    css: styles.css
    toc: true



